version: '3.8'

services:
  mongodb_test:
    image: mongo:latest
    container_name: mongodb_test
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/fifthproj/database/docker/Resources/data_test:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8082"
    env_file:
      - .env
    # environment:`
      # MONGO_URI: mongodb://root:example@mongodb:27018
    networks:
      - app-network
    depends_on:
      - mongodb_test

networks:
  app-network:
    driver: bridge
