version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/fifthproj/database/docker/Resources/MainDataVolume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - new_gateway_network

  app:
    container_name: storage_service 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - new_gateway_network

networks:
  new_gateway_network:
      external: true
      name: identityproviderapi_new_gateway_network